apiVersion: v1
kind: Service
metadata:
  name: donor-frontend-service
  namespace: blood-donation
  labels:
    project: blood-donation
    app: donor-frontend
    component: web
    tier: frontend
    resource-type: service
spec:
  type: ClusterIP
  selector:
    app: donor-frontend
    component: web
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100
  