apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: tech-api
    resource-type: Service
    tier: backend
    environment: development
spec:
  selector:
    app: tech-api
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
