apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: blood-donation
  labels:
    project: blood-donation
    app: blood-donation-api
    component: api
    tier: backend
    resource-type: secret
type: Opaque
data:
  # JWT secret pour tous les services API (user, campaign, appointment, analytics)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  # JWT secret spécifique pour le service admin
  ADMIN_JWT_SECRET: eW91ci1hZG1pbi1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  # Mot de passe DB pour tous les services API
  DB_PASSWORD: Ymxvb2RwYXNz