apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: blood-donation
  labels:
    project: blood-donation
    app: blood-donation-app
    component: api
    tier: backend
    resource-type: secret
type: Opaque
data: 
  JWT_SECRET: "eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg=="
  ADMIN_JWT_SECRET: "eW91ci1hZG1pbi1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg=="