apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blood-donation
  labels:
    project: blood-donation
    app: mysql
    component: database
    tier: backend
    resource-type: secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: Ymxvb2RwYXNz