apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-config
  namespace: blood-donation
  labels:
    project: blood-donation
    app: admin-service
    component: api
    tier: backend
    resource-type: configmap
data:
  NODE_ENV: "production"
  PORT: "3005"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "dondesang"
  DB_USER: "blooduser"
  CORS_ORIGIN: "http://admin-dashboard-service:3200"
  USER_SERVICE_URL: "http://user-service:3001"
  CAMPAIGN_SERVICE_URL: "http://campaign-service:3002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:3003"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3004"
