apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: users-app
    resource-type: deployment
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
      tier: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: users-app
        resource-type: pod
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: hassanaym/frontend-ii-com:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VALIDATION_SERVICE_URL
              value: http://validation-service:3001
            - name: DATABASE_SERVICE_URL
              value: http://database-service:3002
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
