apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: users-app
    resource-type: service
    tier: frontend
spec:
  selector:
    app: users-app
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
