#!/bin/bash

# LAB 1 - Configuration d'un pare-feu pour serveur web
#
# OBJECTIF PÉDAGOGIQUE:
# Apprendre à sécuriser un serveur web avec UFW (Uncomplicated Firewall)
# en appliquant les bonnes pratiques de sécurité réseau
#
# COMPÉTENCES CIBLES:
# - Maîtrise du pare-feu UFW
# - Configuration de règles de sécurité réseau
# - Sécurisation des accès SSH
# - Autorisation contrôlée des services web
#
# DURÉE ESTIMÉE: 15 minutes
# POINTS: 5/30
# PRÉREQUIS: Accès administrateur (sudo), connaissances Linux de base

echo "=== LAB 1 - CONFIGURATION PARE-FEU SERVEUR WEB ==="
echo ""
echo "CONTEXTE PROFESSIONNEL:"
echo "Vous êtes administrateur système dans une startup qui lance"
echo "son premier serveur web en production. Le RSSI demande une"
echo "sécurisation complète avec un pare-feu correctement configuré."
echo ""

echo "MISSION:"
echo "Configurer UFW pour protéger un serveur hébergeant:"
echo "- Un service web (HTTP/HTTPS)"  
echo "- Un accès SSH sécurisé"
echo "- Aucun autre service exposé"
echo ""

echo "ARCHITECTURE CIBLE:"
echo "- SSH: Port 2222 (non-standard pour sécurité)"
echo "- HTTP: Port 80 (trafic web)"
echo "- HTTPS: Port 443 (trafic web sécurisé)"
echo "- Politique par défaut: DENY (principe de moindre privilège)"
echo ""

echo "ÉTAPES À RÉALISER:"
echo "=================="
echo ""

echo "ÉTAPE 1: État initial et installation"
echo "-----------------------------------"
echo "Tâche 1.1: Vérifier le statut actuel d'UFW"
echo "  Commande: sudo ufw status"
echo "  Question: UFW est-il actif ? Quelles règles sont présentes ?"
echo ""
echo "Tâche 1.2: Vérifier l'installation d'UFW"
echo "  Commande: which ufw"
echo "  Action si absent: sudo apt update && sudo apt install ufw"
echo ""

echo "ÉTAPE 2: Configuration des politiques par défaut"
echo "----------------------------------------------"
echo "Tâche 2.1: Définir la politique de refus par défaut"
echo "  Objectif: Bloquer tout trafic entrant non autorisé"
echo "  Commande à exécuter: sudo ufw default deny incoming"
echo ""
echo "Tâche 2.2: Autoriser le trafic sortant"
echo "  Objectif: Permettre les connexions sortantes (mises à jour, etc.)"
echo "  Commande à exécuter: sudo ufw default allow outgoing"
echo ""
echo "Tâche 2.3: Vérifier la configuration des politiques"
echo "  Commande: sudo ufw status verbose"
echo ""

echo "ÉTAPE 3: Configuration de l'accès SSH sécurisé"
echo "--------------------------------------------"
echo "Tâche 3.1: Autoriser SSH sur port non-standard"
echo "  Objectif: Sécuriser l'administration à distance"
echo "  Port cible: 2222 (évite les scans automatiques sur 22)"
echo "  Commande à exécuter: sudo ufw allow 2222/tcp comment 'SSH Admin'"
echo ""
echo "Tâche 3.2: Restriction par réseau source (BONUS)"
echo "  Si vous connaissez votre réseau d'administration:"
echo "  Exemple: sudo ufw allow from 192.168.1.0/24 to any port 2222"
echo "  Remplacez 192.168.1.0/24 par votre réseau réel"
echo ""

echo "ÉTAPE 4: Configuration des services web"
echo "-------------------------------------"
echo "Tâche 4.1: Autoriser le trafic HTTP"
echo "  Objectif: Permettre l'accès au site web"
echo "  Commande à exécuter: sudo ufw allow 80/tcp comment 'HTTP Web'"
echo ""
echo "Tâche 4.2: Autoriser le trafic HTTPS"
echo "  Objectif: Permettre l'accès sécurisé au site"
echo "  Commande à exécuter: sudo ufw allow 443/tcp comment 'HTTPS Web'"
echo ""
echo "Tâche 4.3: Alternative avec profils d'applications"
echo "  Commande: sudo ufw app list"
echo "  Si disponible: sudo ufw allow 'Apache Full'"
echo "  Ou: sudo ufw allow 'Nginx Full'"
echo ""

echo "ÉTAPE 5: Activation et validation"
echo "------------------------------"
echo "Tâche 5.1: Activer le pare-feu UFW"
echo "  ATTENTION: Assurez-vous d'avoir autorisé SSH avant !"
echo "  Commande à exécuter: sudo ufw enable"
echo "  Réponse attendue: 'y' pour confirmer"
echo ""
echo "Tâche 5.2: Vérifier la configuration finale"
echo "  Commande: sudo ufw status numbered"
echo "  Question: Combien de règles sont actives ?"
echo ""
echo "Tâche 5.3: Tester la connectivité"
echo "  SSH: Connexion sur port 2222"
echo "  Web: curl http://localhost (si service installé)"
echo ""

echo "ÉTAPE 6: Tests de sécurité et validation"
echo "--------------------------------------"
echo "Tâche 6.1: Tester les connexions autorisées"
echo "  Test SSH: ssh -p 2222 utilisateur@serveur"
echo "  Test HTTP: curl -I http://adresse-serveur"
echo "  Test HTTPS: curl -I https://adresse-serveur"
echo ""
echo "Tâche 6.2: Vérifier le blocage des ports non autorisés"
echo "  Test d'un port fermé: telnet adresse-serveur 25"
echo "  Résultat attendu: Connexion refusée ou timeout"
echo ""
echo "Tâche 6.3: Consulter les logs UFW"
echo "  Commande: sudo tail -f /var/log/ufw.log"
echo "  Observer les connexions bloquées en temps réel"
echo ""

echo "CONFIGURATION DE SÉCURITÉ AVANCÉE (BONUS):"
echo "=========================================="
echo ""

echo "Limitation du taux de connexions SSH:"
echo "  sudo ufw limit 2222/tcp"
echo "  Effet: Bloque les tentatives répétées (brute force)"
echo ""

echo "Logging détaillé:"
echo "  sudo ufw logging on"
echo "  sudo ufw logging medium"
echo "  Permet un suivi détaillé des connexions"
echo ""

echo "Règles spécifiques par adresse IP:"
echo "  sudo ufw allow from ADRESSE_IP to any port 2222"
echo "  Remplacez ADRESSE_IP par l'IP de confiance"
echo ""

echo "VALIDATION FINALE:"
echo "================="
echo ""

echo "Checklist de validation:"
echo "1. □ UFW est actif (sudo ufw status)"
echo "2. □ Politique par défaut: deny incoming, allow outgoing"
echo "3. □ SSH autorisé sur port 2222"
echo "4. □ HTTP autorisé sur port 80"
echo "5. □ HTTPS autorisé sur port 443"
echo "6. □ Connectivité SSH fonctionnelle"
echo "7. □ Autres ports bloqués par défaut"
echo ""

echo "Questions de compréhension:"
echo "Q1: Pourquoi utiliser le port 2222 au lieu de 22 pour SSH ?"
echo "Q2: Quelle est la différence entre 'deny' et 'reject' ?"
echo "Q3: Comment vérifier qu'une règle UFW fonctionne correctement ?"
echo ""

echo "Résultats attendus:"
echo "- Serveur sécurisé avec accès contrôlé"
echo "- Services web accessibles publiquement"
echo "- Administration SSH sécurisée"
echo "- Protection contre les scans de ports"
echo ""

echo "COMMANDES DE RÉFÉRENCE:"
echo "======================"
echo ""
echo "État du pare-feu:"
echo "  sudo ufw status verbose"
echo ""
echo "Liste des règles numérotées:"
echo "  sudo ufw status numbered"
echo ""
echo "Supprimer une règle:"
echo "  sudo ufw delete [numéro]"
echo ""
echo "Désactiver UFW temporairement:"
echo "  sudo ufw disable"
echo ""
echo "Réinitialiser la configuration:"
echo "  sudo ufw reset"
echo ""

echo "SÉCURITÉ ET BONNES PRATIQUES:"
echo "============================="
echo ""
echo "Principes appliqués:"
echo "- Principe de moindre privilège (deny by default)"
echo "- Obfuscation des services (port SSH non-standard)"
echo "- Limitation des points d'entrée"
echo "- Traçabilité avec logs détaillés"
echo ""
echo "Points de vigilance:"
echo "- Ne jamais se couper l'accès SSH"
echo "- Tester les règles avant la production"
echo "- Documenter toutes les modifications"
echo "- Prévoir des procédures de rollback"
echo ""

echo "=========================="
echo "Vous pouvez maintenant commencer la configuration."
echo "Suivez les étapes dans l'ordre et validez chaque action."
echo "Temps imparti: 15 minutes"
echo "Bonne chance !"