#!/bin/bash

# LAB 4 CHALLENGE - Système de monitoring automatisé avancé
#
# OBJECTIF PÉDAGOGIQUE:
# Développer un système complet de surveillance réseau automatisée
# avec détection d'anomalies et alertes en temps réel
#
# COMPÉTENCES CIBLES:
# - Scripting avancé de monitoring
# - Automatisation de la surveillance sécurité
# - Implémentation de seuils d'alerte
# - Reporting automatisé d'incidents
#
# DURÉE ESTIMÉE: 45 minutes
# POINTS: 10/30 (Challenge Hors Séance)
# PRÉREQUIS: Complétion des LABs 1, 2 et 3

echo "=== LAB 4 CHALLENGE - MONITORING AUTOMATISÉ AVANCÉ ==="
echo ""
echo "CONTEXTE PROFESSIONNEL:"
echo "Vous êtes ingénieur DevOps dans une entreprise qui gère"
echo "une infrastructure critique. Le RSSI demande un système"
echo "de monitoring automatisé capable de détecter et alerter"
echo "sur les incidents sécurité en temps réel."
echo ""

echo "MISSION CHALLENGE:"
echo "Créer un système de surveillance automatisée qui:"
echo "1. Monitor en continu l'activité réseau"
echo "2. Détecte les anomalies de sécurité"
echo "3. Génère des alertes automatiques"
echo "4. Produit des rapports d'incidents"
echo "5. Propose des actions correctives"
echo ""

echo "ARCHITECTURE CIBLE:"
echo "- Script de monitoring principal (daemon)"
echo "- Module de détection d'anomalies"
echo "- Système d'alertes multi-niveaux"
echo "- Base de données d'incidents"
echo "- Interface de reporting"
echo ""

# Définition des paramètres de monitoring
echo "PARAMÈTRES DE MONITORING À IMPLÉMENTER:"
echo "======================================"
echo ""

echo "1. SEUILS D'ALERTE RÉSEAU:"
echo "- Connexions simultanées > 100: Alerte INFO"
echo "- Connexions simultanées > 200: Alerte WARNING"
echo "- Connexions simultanées > 500: Alerte CRITICAL"
echo "- Échecs SSH > 10/minute: Alerte WARNING"
echo "- Échecs SSH > 30/minute: Alerte CRITICAL"
echo ""

echo "2. DÉTECTEURS D'ANOMALIES:"
echo "- Nouvelles IPs sources inconnues"
echo "- Tentatives sur ports fermés"
echo "- Pics soudains de trafic réseau"
echo "- Connexions depuis pays à risque"
echo "- Services inhabituels en écoute"
echo ""

echo "3. ACTIONS AUTOMATIQUES:"
echo "- Blocage temporaire IPs suspectes"
echo "- Notification équipe sécurité"
echo "- Capture détaillée du trafic"
echo "- Sauvegarde logs d'incident"
echo "- Escalade selon gravité"
echo ""

echo "ÉTAPES DU CHALLENGE:"
echo "==================="
echo ""

echo "PHASE 1: Architecture du système de monitoring"
echo "-------------------------------------------"
echo "Tâche 1.1: Créer la structure de fichiers:"
echo "  - /opt/security-monitor/"
echo "    ├── bin/monitor-daemon.sh"
echo "    ├── config/thresholds.conf"
echo "    ├── lib/detection-engine.sh"
echo "    ├── logs/incidents/"
echo "    └── reports/"
echo ""
echo "Tâche 1.2: Configuration des seuils d'alerte"
echo "  - Définir les métriques de surveillance"
echo "  - Configurer les niveaux de criticité"
echo "  - Paramétrer les actions automatiques"
echo ""

echo "PHASE 2: Moteur de détection d'anomalies"
echo "--------------------------------------"
echo "Tâche 2.1: Développer les détecteurs:"
echo "  - Analyser l'activité réseau en temps réel"
echo "  - Comparer aux baselines normales"
echo "  - Identifier les déviations significatives"
echo ""
echo "Tâche 2.2: Classification des incidents:"
echo "  - INFO: Événements informatifs"
echo "  - WARNING: Situations suspectes"
echo "  - CRITICAL: Menaces confirmées"
echo ""

echo "PHASE 3: Système d'alertes automatisées"
echo "-------------------------------------"
echo "Tâche 3.1: Implémentation des notifications:"
echo "  - Alerts console avec couleurs"
echo "  - Logs structurés pour SIEM"
echo "  - Rapports d'incident automatiques"
echo ""
echo "Tâche 3.2: Actions correctives automatiques:"
echo "  - Blocage UFW des IPs malveillantes"
echo "  - Isolation temporaire des services"
echo "  - Capture forensique du trafic"
echo ""

echo "PHASE 4: Interface de monitoring temps réel"
echo "-----------------------------------------"
echo "Tâche 4.1: Dashboard console interactif:"
echo "  - Affichage temps réel des métriques"
echo "  - Historique des incidents récents"
echo "  - Status des détecteurs actifs"
echo ""
echo "Tâche 4.2: Reporting et persistence:"
echo "  - Base de données d'incidents locale"
echo "  - Rapports journaliers automatiques"
echo "  - Statistiques de sécurité"
echo ""

echo "SPÉCIFICATIONS TECHNIQUES DÉTAILLÉES:"
echo "===================================="
echo ""

echo "1. DAEMON DE MONITORING:"
echo "Script: /opt/security-monitor/bin/monitor-daemon.sh"
echo ""
echo "Fonctions requises:"
echo "- monitor_connections(): Surveillance ss en continu"
echo "- analyze_ssh_logs(): Analyse temps réel auth.log"
echo "- check_ufw_blocks(): Monitoring blocages firewall"
echo "- detect_port_scans(): Identification reconnaissance"
echo "- generate_alerts(): Système d'alertes multi-niveaux"
echo ""

echo "2. MOTEUR DE DÉTECTION:"
echo "Script: /opt/security-monitor/lib/detection-engine.sh"
echo ""
echo "Algorithmes à implémenter:"
echo "- Baseline learning: Apprentissage comportement normal"
echo "- Anomaly detection: Détection déviations statistiques"
echo "- Pattern recognition: Identification signatures d'attaque"
echo "- Risk scoring: Classification automatique des menaces"
echo ""

echo "3. MODULE D'ALERTES:"
echo "Intégration dans le daemon principal"
echo ""
echo "Niveaux d'escalade:"
echo "- INFO: Log simple, pas d'action"
echo "- WARNING: Alerte console + log détaillé"
echo "- CRITICAL: Alerte + action corrective + rapport"
echo ""

echo "4. PERSISTENCE ET REPORTING:"
echo "Base de données: SQLite locale pour incidents"
echo "Formats de sortie: JSON, CSV, rapport texte"
echo ""

echo "IMPLÉMENTATION PROGRESSIVE:"
echo "=========================="
echo ""

echo "MILESTONE 1 (15 minutes): Infrastructure de base"
echo "- Créer l'arborescence de fichiers"
echo "- Implémenter le daemon principal"
echo "- Configurer la surveillance basique"
echo "- Tester la collecte de métriques"
echo ""

echo "MILESTONE 2 (15 minutes): Détection et alertes"
echo "- Développer les détecteurs d'anomalies"
echo "- Implémenter le système d'alertes"
echo "- Configurer les actions automatiques"
echo "- Tester les scénarios d'incident"
echo ""

echo "MILESTONE 3 (15 minutes): Monitoring avancé"
echo "- Créer l'interface dashboard"
echo "- Implémenter la persistence des données"
echo "- Développer le reporting automatique"
echo "- Validation complète du système"
echo ""

echo "VALIDATION DU CHALLENGE:"
echo "======================="
echo ""

echo "CRITÈRES DE RÉUSSITE:"
echo "1. Daemon fonctionnel avec monitoring continu"
echo "2. Détection d'au moins 3 types d'anomalies"
echo "3. Système d'alertes multi-niveaux opérationnel"
echo "4. Actions correctives automatiques"
echo "5. Interface de reporting fonctionnelle"
echo ""

echo "TESTS D'ACCEPTATION:"
echo "- Démarrage/arrêt propre du daemon"
echo "- Détection simulée d'intrusion SSH"
echo "- Génération d'alerte automatique"
echo "- Blocage automatique IP malveillante"
echo "- Production rapport d'incident"
echo ""

echo "SCÉNARIOS DE TEST RECOMMANDÉS:"
echo "=============================="
echo ""

echo "Test 1: Simulation attaque par force brute"
echo "- Générer échecs SSH répétés"
echo "- Vérifier détection par le monitoring"
echo "- Contrôler déclenchement alerte WARNING"
echo "- Valider blocage automatique UFW"
echo ""

echo "Test 2: Simulation scan de ports"
echo "- Utiliser nmap depuis machine distante"
echo "- Vérifier détection reconnaissance"
echo "- Contrôler alerte INFO appropriée"
echo "- Valider logging détaillé"
echo ""

echo "Test 3: Surcharge de connexions"
echo "- Simuler pic de trafic réseau"
echo "- Vérifier détection anomalie performance"
echo "- Contrôler escalade vers WARNING/CRITICAL"
echo "- Valider rapport automatique"
echo ""

echo "LIVRABLES ATTENDUS:"
echo "=================="
echo ""
echo "1. Code source complet du système"
echo "2. Documentation technique d'installation"
echo "3. Guide d'utilisation administrateur"
echo "4. Rapport de tests et validation"
echo "5. Recommandations d'amélioration future"
echo ""

echo "EXTENSION BONUS (OPTIONNEL):"
echo "==========================="
echo ""
echo "Pour les équipes avancées:"
echo "1. Intégration avec ELK Stack"
echo "2. Dashboard web avec graphiques"
echo "3. Machine Learning pour détection"
echo "4. API REST pour intégration SIEM"
echo "5. Module de threat intelligence"
echo ""

echo "RESSOURCES ET RÉFÉRENCES:"
echo "========================"
echo ""
echo "Documentation recommandée:"
echo "- man ss, tcpdump, iptables"
echo "- Guide UFW et fail2ban"
echo "- Bash scripting avancé"
echo "- Monitoring et observabilité"
echo "- Incident response procedures"
echo ""

echo "Outils complémentaires:"
echo "- jq pour manipulation JSON"
echo "- sqlite3 pour persistence"
echo "- curl pour notifications"
echo "- cron pour tâches périodiques"
echo ""

echo "=========================="
echo "DÉMARRAGE DU CHALLENGE"
echo "=========================="
echo ""
echo "Vous disposez de 45 minutes pour implémenter"
echo "ce système de monitoring automatisé avancé."
echo ""
echo "Points d'évaluation:"
echo "- Architecture et structure (2 points)"
echo "- Qualité du code et bonnes pratiques (2 points)"
echo "- Fonctionnalités de détection (2 points)"
echo "- Système d'alertes (2 points)"
echo "- Tests et validation (2 points)"
echo ""
echo "GOOD LUCK - MONTREZ VOS COMPÉTENCES DEVOPS!"
echo ""
echo "Commencez par créer la structure de base:"
echo "sudo mkdir -p /opt/security-monitor/{bin,config,lib,logs/incidents,reports}"
echo ""
echo "Puis développez le daemon principal:"
echo "sudo nano /opt/security-monitor/bin/monitor-daemon.sh"
echo ""
echo "Challenge démarré! Timer: 45 minutes"
