#!/bin/bash

# LAB 3 - Monitoring sécurisé du trafic
#
# Objectifs :
# - Surveiller le trafic réseau et analyser les connexions
# - Détecter des anomalies de sécurité et performance
# - Utiliser les outils de monitoring Linux avancés
#
# Points : 5/30
# Durée estimée : 20 minutes
#
# Contexte : Applications web DevOps avec ralentissements suspects et
# tentatives de connexion non-autorisées détectées dans l'infrastructure

echo "=== LAB 3 - MONITORING SÉCURISÉ DU TRAFIC ==="
echo ""

# CONTEXTE ET PROBLÉMATIQUE
echo "CONTEXTE: Incident de sécurité et performance sur infrastructure DevOps"
echo ""
echo "SYMPTÔMES DÉTECTÉS:"
echo "- Ralentissements inexpliqués des applications web"
echo "- Pic d'activité réseau anormal dans les métriques"
echo "- Alertes sécurité pour tentatives de connexion suspectes"
echo "- Consommation CPU élevée sur les serveurs web"
echo ""
echo "MISSION: Identifier la source des problèmes par analyse réseau"
echo ""

# ÉTAPE 1: Analyse des connexions actives
echo "ÉTAPE 1: Surveillance des connexions réseau actives"
echo "Identification des services en écoute et connexions établies"
echo ""
echo "Commande d'analyse moderne (ss):"
echo "ss -tulpn"
echo ""
echo "Analyse spécialisée:"
echo "ss -tulpn | grep LISTEN     # Services en écoute"
echo "ss -tu state established    # Connexions établies"
echo "ss -s                       # Statistiques globales"
echo ""
echo "TÂCHE 1: Exécutez ces commandes et identifiez:"
echo "- Quels services sont en écoute sur quels ports?"
echo "- Combien de connexions établies par service?"
echo "- Y a-t-il des ports inattendus ouverts?"
echo ""
echo "Résultat attendu: Liste complète des services réseau actifs"
echo ""

# ÉTAPE 2: Capture et analyse du trafic web
echo "ÉTAPE 2: Capture du trafic HTTP pour analyse"
echo "Investigation des ralentissements web par capture de paquets"
echo ""
echo "Commande de capture ciblée:"
echo "sudo tcpdump -i eth0 port 80 -c 50"
echo ""
echo "Analyse plus détaillée:"
echo "sudo tcpdump -i eth0 port 80 -v -n -c 30"
echo ""
echo "TÂCHE 2: Capturez 30 secondes de trafic HTTP et analysez:"
echo "- Volume de requêtes par seconde"
echo "- Adresses IP sources les plus actives"
echo "- Types de requêtes (GET, POST, etc.)"
echo "- Tailles des paquets anormales"
echo ""
echo "Note: Si aucun trafic HTTP, simuler avec: curl http://localhost"
echo ""

# ÉTAPE 3: Analyse des logs d'authentification
echo "ÉTAPE 3: Investigation des tentatives d'intrusion"
echo "Analyse des logs de sécurité pour détecter les attaques"
echo ""
echo "Commandes d'analyse des logs:"
echo "grep 'Failed password' /var/log/auth.log | tail -10"
echo ""
echo "Analyse plus approfondie:"
echo "grep 'Failed password' /var/log/auth.log | awk '{print \$9}' | sort | uniq -c | sort -nr"
echo ""
echo "TÂCHE 3: Analysez les tentatives de connexion et identifiez:"
echo "- Nombre total de tentatives échouées aujourd'hui"
echo "- Adresses IP avec le plus d'échecs"
echo "- Patterns temporels (heures d'attaque)"
echo "- Comptes ciblés par les attaquants"
echo ""

# ÉTAPE 4: Surveillance des connexions SSH
echo "ÉTAPE 4: Audit des connexions SSH réussies"
echo "Vérification de l'intégrité des accès administrateur"
echo ""
echo "Commandes d'audit SSH:"
echo "grep 'sshd.*Accepted' /var/log/auth.log | tail -5"
echo ""
echo "Analyse détaillée:"
echo "grep 'Accepted publickey\\|Accepted password' /var/log/auth.log | tail -10"
echo ""
echo "TÂCHE 4: Vérifiez les connexions SSH légitimes:"
echo "- Quand ont eu lieu les dernières connexions?"
echo "- Quels utilisateurs se sont connectés?"
echo "- Méthodes d'authentification utilisées?"
echo "- Adresses IP sources des connexions"
echo ""

# ÉTAPE 5: Monitoring temps réel des connexions
echo "ÉTAPE 5: Surveillance temps réel de l'activité réseau"
echo "Observation continue pour détecter les pics d'activité"
echo ""
echo "Commande de surveillance continue:"
echo "watch -n 2 'ss -tu state established | wc -l'"
echo ""
echo "Analyse parallèle recommandée:"
echo "watch -n 3 'ss -tulpn | grep :80'"
echo ""
echo "TÂCHE 5: Surveillez pendant 2 minutes et notez:"
echo "- Nombre de connexions simultanées"
echo "- Variations dans le temps"
echo "- Pic d'activité anormaux"
echo ""
echo "Note: Appuyez sur Ctrl+C pour arrêter watch"
echo ""

# ÉTAPE 6: Identification des processus consommateurs
echo "ÉTAPE 6: Corrélation processus et activité réseau"
echo "Identification des applications générant le trafic"
echo ""
echo "Commandes d'analyse processus-réseau:"
echo "ss -tulpn | grep ESTABLISHED"
echo ""
echo "Analyse par processus:"
echo "ss -p | grep ESTABLISHED | head -10"
echo ""
echo "TÂCHE 6: Identifiez quels processus génèrent le plus de trafic:"
echo "- PIDs des processus les plus actifs"
echo "- Applications correspondantes"
echo "- Consommation réseau par processus"
echo ""

# ÉTAPE 7: Recherche de scans de ports suspects
echo "ÉTAPE 7: Détection de tentatives de reconnaissance"
echo "Analyse des logs pare-feu pour identifier les scans"
echo ""
echo "Commandes d'analyse UFW:"
echo "sudo grep 'UFW BLOCK' /var/log/ufw.log | tail -10"
echo ""
echo "Analyse des patterns de scan:"
echo "sudo grep 'UFW BLOCK' /var/log/ufw.log | awk '{print \$12}' | cut -d= -f2 | sort | uniq -c | sort -nr"
echo ""
echo "TÂCHE 7: Recherchez les activités de scan:"
echo "- Tentatives de connexion bloquées"
echo "- IPs sources des scans"
echo "- Ports ciblés par les attaquants"
echo "- Fréquence des tentatives"
echo ""

# ÉTAPE 8: Synthèse et recommandations sécurité
echo "ÉTAPE 8: Documentation des observations et recommandations"
echo ""
echo "TÂCHE 8: Rédigez un rapport d'incident incluant:"
echo ""
echo "1. OBSERVATIONS TECHNIQUES:"
echo "   - Services réseau actifs identifiés"
echo "   - Volume et source du trafic HTTP"
echo "   - Tentatives d'intrusion détectées"
echo "   - Anomalies de performance relevées"
echo ""
echo "2. ANALYSE DE SÉCURITÉ:"
echo "   - IPs suspectes identifiées"
echo "   - Méthodes d'attaque observées"
echo "   - Vulnérabilités potentielles"
echo ""
echo "3. RECOMMANDATIONS D'AMÉLIORATION:"
echo "   - Mesures de sécurité à renforcer"
echo "   - Monitoring à mettre en place"
echo "   - Actions correctives immédiates"
echo ""

echo "=== CRITÈRES D'ÉVALUATION ==="
echo ""
echo "1. Surveillance connexions appropriée (2 points)"
echo "   - Utilisation correcte de ss et tcpdump"
echo "   - Identification des services actifs"
echo "   - Analyse du trafic réseau"
echo ""
echo "2. Analyse logs sécurité méthodique (2 points)"
echo "   - Investigation tentatives d'intrusion"
echo "   - Audit des connexions SSH légitimes"
echo "   - Détection de scans de ports"
echo ""
echo "3. Identification anomalies et recommandations (1 point)"
echo "   - Corrélation des observations"
echo "   - Recommandations sécurité pertinentes"
echo "   - Documentation complète de l'incident"
echo ""

echo "=== OUTILS DE MONITORING UTILISÉS ==="
echo ""
echo "SURVEILLANCE RÉSEAU:"
echo "- ss: Connexions et statistiques modernes"
echo "- tcpdump: Capture et analyse de paquets"
echo "- watch: Monitoring temps réel"
echo ""
echo "ANALYSE SÉCURITÉ:"
echo "- grep: Recherche dans les logs système"
echo "- awk: Traitement et analyse de données"
echo "- sort/uniq: Agrégation et comptage"
echo ""
echo "LOGS IMPORTANTS:"
echo "- /var/log/auth.log: Authentifications SSH"
echo "- /var/log/ufw.log: Activité pare-feu"
echo "- /var/log/syslog: Messages système généraux"
echo ""

echo "=== COMMANDES DE DIAGNOSTIC AVANCÉES ==="
echo ""
echo "# Surveillance bande passante par interface:"
echo "iftop -i eth0"
echo ""
echo "# Analyse réseau par processus:"
echo "nethogs"
echo ""
echo "# Connexions par état détaillées:"
echo "ss -ant | awk '{print \$1}' | sort | uniq -c"
echo ""
echo "# Top des IPs connectées:"
echo "ss -tn | awk 'NR>1 {print \$4}' | cut -d: -f1 | sort | uniq -c | sort -nr"
