apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: blood-donation
  labels:
    project: blood-donation
    app: user-service
    component: api
    tier: backend
    resource-type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      tier: backend
      component: api
  template:
    metadata:
      labels:
        project: blood-donation
        app: user-service
        component: api
        tier: backend
    spec:
      containers:
        - name: user-service-container
          image: hassanaym/bdon-user-service:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"