version: "3.8"

services:
  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - validation
      - database

  validation:
    build: ./validation-service
    ports:
      - "3001:3001"

  database:
    build: ./database-service
    ports:
      - "3002:3002"
